spring.application.name=FinanceTracker
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/FinanceTrackerDB}
spring.datasource.username=${DB_USERNAME:Alexandr}
spring.datasource.password=${DB_PASSWORD:root}


# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.locations=classpath:db/migration
spring.flyway.table=flyway_schema_history
spring.flyway.validate-on-migrate=true

# ===== LOGGING =====
logging.level.root=INFO
logging.level.org.brusnitsyn.financetracker=DEBUG
logging.level.org.springframework.security=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
logging.file.name=logs/Finance.log

spring.flyway.clean-disabled=false

# Management security
management.security.enabled=false

# Swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

jwt.expiration=30
jwt.secret=y2a5RrRZ9YlqK0uZb8H6u0ZcYbQFv+F0l1Q2Xz0k1Lo=

# ===== ACTUATOR =====
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized

management.info.env.enabled=true
info.app.name=Finance Tracker
info.app.version=1.0.0
info.app.description=Personal finance tracking API